name: Repository Dispatch
on:
  repository_dispatch:
    types: garabkda
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Dump the client payload context
        env:
          GH_EVENT: ${{ toJson(github.event) }}
        run: echo "$GH_EVENT"

      - uses: actions/checkout@v5
        if: github.event.client_payload.ref != ''
        with:
          ref: ${{ github.event.client_payload.ref }}

      - run: echo ${{ github.event.client_payload.sha }}
